run:
  allow-parallel-runners: true

linters-settings:
  gci:
    local-prefixes: github.com/nestoroprysk/mood-tracker

linters:
  enable-all: true
  disable:
    - interfacer
    - scopelint
    - maligned
    - golint
    - prealloc
    - wrapcheck
    - varnamelen
    - gomnd
    - goerr113
    - exhaustivestruct
    - lll
    - ireturn
    - paralleltest
    - gocritic
    - tagliatelle
    - noctx
    - gochecknoglobals
    - nlreturn
